language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN= "f8d19405-06d6-4849-b1cd-0c4df1eb4235"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - amakutsevich@bk.ru
    on_success: never # default: change
    on_failure: always # default: always